---
- hosts: sso
  become: yes

  tasks:
  - name: Install packages
    package: name="{{ item }}" state=present
    with_items:
    - docker
    - docker-compose
    - httpd
    - python-docker-py
    - git

  - name: Allow Apache to connect to Keycloak
    seboolean:
      name: httpd_can_network_relay
      state: yes
      persistent: yes

  - name: Configure Apache Proxy
    template:
      src: files/sso.conf.j2
      dest: /etc/httpd/conf.d/sso.conf
    notify:
    - httpd_restart

  - name: Start services
    service: name="{{ item }}" state=started
    with_items:
    - docker
    - httpd

  - name: Ensures /root/sso dir exists
    file: path=/root/sso state=directory

  - name: Copy docker-compose.yml to /root/sso
    template:
      src: files/docker-compose.yml.j2
      dest: /root/sso/docker-compose.yml

  handlers:
  - name: httpd_restart
    service: name=httpd state=restarted
    become: yes
